### PR TITLE
resolve #38

### LINKED ISSUE #38: Crash on Non-200 GET Response from Micro-service
https://github.com/arbor-dev/arbor/blob/master/proxy/GET.go#L53-L58

When err is nil and the response code is not 200 the if block is entered and the err.Error() call creates a null pointer exception.

### PR DESCRIPTION
**Pull request by narendasan**
High level overview of changes 
Addresses #38 

- [X] Make sure to tag the issue you are addressing in your comments if applicable. 
- [X] Make sure any tests pass
- [X] Make sure you stick to rough style guidelines
- [ ] Have you added the license header to any new files? 
- [ ] Tag a reviewer 
- [X] Select target milestone
- [ ] Make sure to document any new features or API changes

### CODE REVIEW

File: proxy/PUT.go [hunk 1]
```diff
@@ -111,8 +111,12 @@ func jsonPUT(r *http.Request, w http.ResponseWriter, url string, token string, d
 
 	client := &http.Client{Timeout: time.Duration(Timeout) * time.Second}
 	resp, err := client.Do(req)
-	if err != nil || resp.StatusCode != http.StatusOK {
-		logger.Log(logger.ERR, "SERVICE FAILED - SERVICE RETURNED STATUS "+http.StatusText(resp.StatusCode))
+	if err != nil {
+		//TODO: INVALID PUT HANDLER
```
Comment (bcongdon) [inline proxy/PUT.go]: Can you open an issue for this?

File: server/server.go [hunk 2]
```diff
@@ -31,16 +31,13 @@ func NewServer(routes services.RouteCollection, addr string, port uint16) *Arbor
...
 	logger.Log(logger.SPEC, "Roots being planted [Server is listening on "+a.addr+"]")
 
-	go func() {
-		err := a.server.ListenAndServe()
-		if err != nil {
-			if err.Error() == "http: Server closed" {
-				return
-			}
-			logger.Log(logger.FATAL, err.Error())
+	err := a.server.ListenAndServe()
```
Comment (bcongdon) [inline server/server.go]: I'm +1 on this change.

It felt weird to return after starting the server.
